import { 
    requestEmails, 
    sendEmail, 
    getEmailById, 
    updateEmail, 
    archiveEmail, 
    archiveEmailById, 
    unarchiveEmail, 
    unarchiveEmailById, 
    toggleArchive, 
    toggleArchiveById, 
    toggleRead, 
    toggleReadById, 
    readEmail, 
    readEmailById, 
    unreadEmail, 
    unreadEmailById, 
    markForDeletion,
    markForDeletionById,
    unmarkForDeletion,
    unmarkForDeletionById
    } from "./modules/emails";

export {
    requestEmails,
    sendEmail,
    getEmailById,
    updateEmail,
    archiveEmail,
    archiveEmailById,
    unarchiveEmail,
    unarchiveEmailById,
    toggleArchive,
    toggleArchiveById,
    toggleRead,
    toggleReadById,
    readEmail, 
    readEmailById, 
    unreadEmail, 
    unreadEmailById, 
    markForDeletion,
    markForDeletionById,
    unmarkForDeletion,
    unmarkForDeletionById
}