// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActionMenu: typeof import('./components/interface/inbox/ActionMenu.vue')['default']
    ActionMenuItem: typeof import('./components/interface/inbox/ActionMenuItem.vue')['default']
    Button: typeof import('./components/base/Button.vue')['default']
    Checkbox: typeof import('./components/base/Checkbox.vue')['default']
    ComposeEmailModal: typeof import('./components/interface/ComposeEmailModal.vue')['default']
    EmailItem: typeof import('./components/interface/inbox/EmailItem.vue')['default']
    EmailModal: typeof import('./components/interface/EmailModal.vue')['default']
    Inbox: typeof import('./components/interface/inbox/Inbox.vue')['default']
    Layout: typeof import('./components/interface/Layout.vue')['default']
    Modal: typeof import('./components/base/Modal.vue')['default']
    Tab: typeof import('./components/interface/inbox/Tab.vue')['default']
    TabBar: typeof import('./components/interface/inbox/TabBar.vue')['default']
    TextInput: typeof import('./components/base/TextInput.vue')['default']
  }
}

export { }
